import csv,json,random,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OLD=ROOT/'outputs/decision-engine/formal-benchmark-20260918';OUT=ROOT/'outputs/decision-engine/accuracy-diagnosis-20260918'
data=json.loads((OLD/'cases.json').read_text());rng=random.Random(9182026);cases=[]
qs={g:next(c['questions']['decision'] for c in data['cases'] if c['group']==g) for g in ['banking','routing','scoring']}
def add(group,context,q,label):
 q=json.loads(json.dumps(q))
 if q['type']=='choice':items=list(q['criteria'].items());rng.shuffle(items);q['criteria']=dict(items)
 cases.append({'id':f'fresh_{len(cases):03d}','group':group,'context':context,'questions':{'decision':q},'expected':{'decision':label}})
used={c['source']['row_index'] for c in data['cases'] if c['group']=='banking'}
categories={c['source']['original_label']:c['expected']['decision'] for c in data['cases'] if c['group']=='banking'}
rows=list(csv.DictReader((OLD/'banking77-test.csv').open()))
for category,label in categories.items():
 for i,r in rng.sample([(i,r) for i,r in enumerate(rows) if r['category']==category and i not in used],2):
  add('banking',r['text'],qs['banking'],label);cases[-1]['source_row']=i
for label,texts in {
'fast':['Translate the word river into Italian.','Make this sentence more polite: Send the invoice.','What is 8 multiplied by 3?','Name the largest planet.','Write a two-word greeting for a new colleague.','Is April before May?'],
'coding':['Build a Python function that merges overlapping time intervals.','Write a Postgres query counting visits per user.','Debug a missing dependency in my React effect.','Produce a patch for an off-by-one bug in this Go loop.','Implement binary search in Kotlin and add tests.','Review the authorization checks in this Express middleware.'],
'reasoning':['Prove that the square root of three is irrational.','Plan a multi-year factory expansion with uncertain demand, financing limits, and supply dependencies.','Derive the expected number of rolls required to observe two consecutive sixes.','Solve a constraint puzzle about seven people assigned to seats.','Assess a causal argument with selection bias and reverse causation.','Construct a counterexample showing why the proposed converse of a theorem fails.']}.items():
 for ctx in texts:add('routing',ctx,qs['routing'],label)
bools=[('Does the CURRENT customer explicitly ask to speak to a human agent?','Let a member of your support staff take over this conversation.','yes'),('Does the CURRENT customer explicitly ask to speak to a human agent?','The automated assistant is enough for me; no person is needed.','no'),('Does the latest customer statement explicitly request cancellation of their subscription?','Please discontinue my subscription after this month.','yes'),('Does the latest customer statement explicitly request cancellation of their subscription?','The instructions explain how to cancel, but I want to remain subscribed.','no'),('Does the latest statement explicitly confirm the parcel has been delivered to the customer? Predictions and denials do not count.','The delivery driver gave me my order at noon.','yes'),('Does the latest statement explicitly confirm the parcel has been delivered to the customer? Predictions and denials do not count.','The driver says my order will be here in an hour.','no'),('Does the person explicitly grant permission to receive marketing emails in their latest statement?','You have my permission to send me advertising emails.','yes'),('Does the person explicitly grant permission to receive marketing emails in their latest statement?','I only authorize password-reset emails, not advertisements.','no'),('Does the customer currently request their payment back?','Return the money I paid for the broken item, please.','yes'),('Does the customer currently request their payment back?','My sister asked for her money back; I just want a replacement receipt.','no'),('Does the text explicitly state that the door is locked?','I checked the door and it is locked.','yes'),('Does the text explicitly state that the door is locked?','I have not checked whether the door is locked.','no')]
for q,ctx,label in bools:add('boolean',ctx,{'type':'noul','instructions':q},label)
scored=[('A user asks where to find the export feature and says everything works.','0'),('The manual needs explaining; no broken features or losses have been reported.','0'),('The logo overlaps a heading, but every operation still works.','1'),('The app uses the wrong shade of purple; functionality is unaffected.','1'),('One account cannot use the shortcut but can perform the operation with a menu command.','2'),('A single user encounters a broken button and finishes the task using the keyboard alternative.','2'),('Exactly one customer cannot finish their task by any available method; all other accounts work.','3'),('A single account is unusable, and support confirms there is no workaround.','3'),('Twelve customer accounts cannot complete any tasks and have no alternative method.','4'),('Several users report total loss of access with no way to finish their work.','4')]
for ctx,label in scored:add('scoring',ctx,qs['scoring'],label)
# New workflow checks transfer beyond the development domains.
newq={'type':'choice','instructions':'Identify the main requested document operation.','criteria':{'translate':'Convert text into a different language','summarize':'Shorten text while retaining its key information','proofread':'Correct spelling, grammar, or punctuation without changing language'}}
for label,texts in {'translate':['Convert this letter from English to Dutch.','Put this paragraph into Korean.','Give me the same report in Portuguese.','Render this French message in English.','Translate the notes to Swedish.','I need a German version of the instructions.','Change the language of this invitation to Spanish.'],'summarize':['Reduce this report to three key points.','Give me a brief account of the main ideas.','Make a short overview of the attached notes.','Condense these minutes to a paragraph.','Extract the central message into a short summary.','Shorten this article while preserving its conclusions.','Write a concise synopsis of this chapter.'],'proofread':['Fix the misspelled words in this paragraph.','Check the commas and grammar in this note.','Correct typos without changing the language.','Repair grammatical errors in this email.','Proofread the document before I send it.','Make the punctuation correct throughout this letter.']}.items():
 for ctx in texts:add('new_workflow',ctx,newq,label)
assert len(cases)==80
path=OUT/'fresh-validation.json'
if path.exists():raise SystemExit('Already frozen')
path.write_text(json.dumps({'seed':9182026,'cases':cases,'note':'Frozen before evaluating the selected correction. New examples, partly templated; not an independent external benchmark.'},indent=2)+'\n')
(OUT/'fresh-validation.sha256').write_text(hashlib.sha256(path.read_bytes()).hexdigest()+'\n')
print('Frozen',len(cases),'fresh validation cases')
