"""Build the reviewable report from frozen benchmark results."""
import json,statistics
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/"outputs/decision-engine/natural-labels-20260918"
def main():
    s=json.loads((OUT/"summary.json").read_text())
    if s["quality_rows"]!=690:raise RuntimeError("Incomplete paired quality benchmark")
    parity=json.loads((OUT/"gpu-parity.json").read_text())
    tests=(OUT/"tests-linux.log").read_text()
    if "\nOK\n" not in tests:raise RuntimeError("Final tests did not pass")
    lines=["# Actual labels versus letter IDs", "", "The neutral-context probability adjustment has been removed. Actual labels were tested as the default; the subsequent user request restored letters as the default after the unfavorable accuracy/latency tradeoff. The controlled comparison found no overall accuracy improvement from this change: actual labels scored 207/250 versus 208/250 with uncorrected letters. Both versions used the same frozen Qwen model and had the correction disabled.", "", "## Accuracy", "", "| Suite | Uncorrected letters | Actual labels |", "|---|---:|---:|"]
    for name,key in [("Original benchmark","core"),("Additional validation","fresh"),("Robustness","robustness")]:
        a,b=[s["suites"][key][m] for m in ("letters","labels")]
        lines.append(f'| {name} | {a["correct"]}/{a["count"]} ({100*a["correct"]/a["count"]:.1f}%) | {b["correct"]}/{b["count"]} ({100*b["correct"]/b["count"]:.1f}%) |')
    lines += ["", f'The 42 original failures were rerun first. Labels fixed {s["core_fixed"]}, but {s["core_regressed"]} previously correct cases regressed. Expected answers and case ordering within each supplied rubric were not edited.', "", "| Original task group | Letters | Labels | Historical pinned HF replica |", "|---|---:|---:|---:|"]
    for group,values in s["core_groups"].items():
        nums=[f'{values[m]["correct"]}/{values[m]["count"]}' for m in ("letters","labels","historical_hf")]
        lines.append('| '+group+' | '+' | '.join(nums)+' |')
    hf=s["historical_hf_core"]
    lines += ["", f'The HF result is the existing pinned same-model benchmark ({hf["correct"]}/{hf["count"]}), not a new HF run. Our aggregate remains higher, but the HF replica performs better on routing and boolean questions. The earlier rejected neutral-correction version scored 219/250; that is historical context, not one of the two arms in this experiment.', "", "All 345 outputs in each arm passed schema validation (690/690 total). This checks returned fields, allowed labels, finite normalized probabilities, and consistency between choice and maximum probability. Task correctness remains separate; unsupported inputs fail explicitly.", "", "## Probability quality", "", "Lower is better for both metrics below. These are candidate likelihoods, not calibrated confidence estimates.", "", "| Original 250 cases | Brier score | Negative log likelihood |", "|---|---:|---:|"]
    for m in ("letters","labels"):
        q=s["suites"]["core"][m];lines.append(f'| {m} | {q["brier"]:.6f} | {q["nll"]:.6f} |')
    lines += ["", "Changing to literal labels did not improve overall probability quality. Several confident routing errors remain. Numeric scoring accuracy stayed perfect on these templated examples, but the probabilities became less concentrated on the expected level.", "", "## Warm latency", "", "Median synchronized wall time on the RTX 3050 Laptop GPU, under WSL/Linux, FP16, with the existing fusions and CUDA graphs enabled. Each method has ten measured warm calls across two blocks with reversed method order. The model was already loaded. These are local prototype measurements, not universal hardware guarantees.", "", "| Workload | Letters ms | Labels ms | Label latency change |", "|---|---:|---:|---:|"]
    for name,v in s["speed"].items():
        if set(v)!={"letters","labels"}:raise RuntimeError("Incomplete speed pair")
        a,b=v["letters"]["warm_median_ms"],v["labels"]["warm_median_ms"]
        lines.append(f'| {name} | {a:.1f} | {b:.1f} | {(b/a-1)*100:+.1f}% |')
    lines += ["", "The standard speed cases use single-token labels. The explicit multi-token example uses `billing support`, `shipping support`, and `product returns`. The banking and routing task rows are actual previously failed benchmark cases. Qwen encodes `declined`, `withdrawal`, and `reasoning` as two tokens, so those task rubrics use full-sequence scoring.", "", "For one-token labels, the selected-head projection and existing question-parallel optimizations remain available. The short one-field example became faster; most other one-token workloads were close. Small differences of a few percent should not be treated as a general speedup. Multi-token scoring currently reuses the prompt KV cache but runs known continuation batches eagerly, with full-vocabulary normalization. That added cost is partly a limitation of the current implementation, not a fundamental lower bound for literal labels.", "", "## First new shape", "", "These medians include request-shape graph capture after a model warmup. They are not fresh-process startup latency and exclude model loading. Compilation/cache state makes these noisier than warm results.", "", "| Workload | Letters ms | Labels ms |", "|---|---:|---:|"]
    for name,v in s["speed"].items():
        lines.append(f'| {name} | {v["letters"]["first_shape_median_ms"]:.1f} | {v["labels"]["first_shape_median_ms"]:.1f} |')
    lines += ["", "## Implementation and correctness", "", "- Removed the neutral-context adjustment implementation, flag, prior cache, and active documentation. Historical source/results are archived.", "- In literal-label mode, Choice answers use actual labels; Score uses its numeric level labels; Noul keeps false/true. No model weights or workflow schemas changed.", "- Single-token labels use selected LM-head rows. Multi-token labels use complete token-sequence likelihoods, without neutral correction or length normalization. They never silently fall back to letters.", "- If a candidate is a token-prefix of another, EOS is included for all candidates of that question to distinguish completed labels. Token aliases, special-token labels, and excessive lengths fail explicitly.", "- The old letter implementation remains an explicit comparison mode: `--answer-encoding letters`. Literal labels are now opt-in with `--answer-encoding labels`; letters remain the default.", "- All 45 Linux/CUDA tests passed, including independent full-model likelihood comparisons, shared first tokens, strict prefix overlap, mixed field types, and removed-flag checks."]
    for c in parity:lines.append(f'- Real-Qwen GPU check `{c["case_id"]}`: maximum probability difference from independent complete-prompt scoring was {c["max_probability_delta"]*100:.5f} percentage points (limit: 1 point).')
    lines += ["", "## Interpretation and limits", "", "The earlier letter prompt already contained the real option names and descriptions. Replacing A/B/C changes the requested answer representation; it does not give the model semantic information it previously lacked. Literal labels can help individual examples, but can also introduce different word-frequency and sequence-length preferences. This experiment does not establish a general accuracy benefit.", "", "The benchmark has 100 real BANKING77 examples and 150 constructed routing/boolean/scoring cases. Additional and robustness sets were reused from earlier experiments, not newly unseen holdouts for this iteration. Strong performance on templated scoring examples should not be generalized to arbitrary rubrics. One-case differences on 250 items are not convincing evidence of a general advantage.", "", "## Artifacts and reproduction", "", "- `quality.jsonl`: all 690 paired results, native outputs, token lengths and first-shape timing.", "- `speed.jsonl` and `task-speed.jsonl`: all repeated timings, ranges available in `summary.json`.", "- `changed-decisions.json`: every fixed/regressed case with before/after probability vectors.", "- `examples.json`: actual rendered prompts and candidate token IDs.", "- `gpu-parity.json` and `tests-linux.log`: correctness checks.", "- `protocol.json`, `environment.json`, and `source/manifest.json`: frozen data hashes, environment and source snapshot.", "", "Run `scripts/benchmark_literal_labels.py`, then `scripts/verify_literal_labels_gpu.py`, using the prepared WSL Python environment. Generate `summary.json` with `scripts/summarize_literal_labels.py`. Existing rows are retained for resumption, so use a new output directory when changing the implementation. No commit or push was made.", ""]
    (OUT/"REPORT.md").write_text("\n".join(lines),encoding="utf-8")
if __name__=="__main__":main()
